### ISSUE TITLE
Unable to test due to loadig issue with GoogleMapsLoader 

### ISSUE THREAD

**Issue by msita143** [xuopled/react-google-maps-loader#19]
Getting error when I ru my test  as below:
console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6309
      The above error occurred in the <GoogleMapsLoader> component:
          in GoogleMapsLoader (at GooglePlacesSuggest.js:72)

 ● UserDetails component › matches the snapshot

    TypeError: Cannot read property 'parentNode' of undefined
      
      at _addScript (node_modules/little-loader/lib/little-loader.js:43:17)
      at _lload (node_modules/little-loader/lib/little-loader.js:209:7)
      at loadGoogleMapsSdk (node_modules/react-google-maps-loader/lib/loadGoogleMapsSdk/index.js:43:34)
      at GoogleMapsLoader.componentDidMount (node_modules/react-google-maps-loader/lib/index.js:45:37)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6444:22)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7540:7)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1899:14)

**Comment by msita143** [comment]
I am using jest

**Comment by brendangibson** [comment]
Add this code to your jest test file - 

```
beforeAll(() => {
  const script = document.createElement("script")
  document.body.appendChild(script)
})
```

**Comment by xuopled** [comment]
could you make a PR to resolve this?
