### ISSUE TITLE
Dependency on fsevents

### ISSUE THREAD

**Issue by bmamone** [xuopled/react-google-maps-loader#25]
react-google-maps-loader v4.2.4 (which is the latest available on NPM) depends on `fsevents`, which causes build problems on Linux platforms. 

```
2019-02-11T17:48:27.134Z  error fsevents@1.2.7: The platform "linux" is incompatible with this module.
2019-02-11T17:48:27.155Z  error Found incompatible module
2019-02-11T17:48:27.155Z  info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2019-02-11T17:48:27.172Z  Error: Exited with 1
                              at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/fs/run-user-scripts.js:11:16)
                              at emitTwo (events.js:126:13)
                              at ChildProcess.emit (events.js:214:7)
                              at maybeClose (internal/child_process.js:925:16)
                              at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

```

**Comment by xuopled** [comment]
What do you have any solution?

**Comment by bmamone** [comment]
I'm using 4.2.3 as it doesn't depend on it.

The current `package.json` available here on GitHub is also 4.2.3, while on NPM the latest is 4.2.4. I guess fsvents is not a dependency at all

**Comment by xuopled** [comment]
I don't know what's happened with the 4.2.4. I can't find any source code about that.

**Comment by xuopled** [comment]
Is it work if you fix your version to `4.2.3` ?

**Comment by bmamone** [comment]
Yes, 4.2.3 is fine!

It's actually really strange, I also couldn't find any commits on this repo that match `4.2.4` or that add `fsevents`. It only exists on NPM.

According to [https://www.npmjs.com/package/react-google-maps-loader](url) it was updated 5 days ago

**Comment by xuopled** [comment]
I think I found why. Could you try using the `v4.2.5` ?

**Comment by bmamone** [comment]
That's perfect! Thank you!
